import type { ModelInfo } from '../types'

export const MODELS: ModelInfo[] = [
  {
    id: 'Qwen3-0.6B-q4f16_1-MLC',
    name: 'Qwen 3 0.6B',
    description: 'Alibaba Qwen 3 - latest generation, ultra lightweight for browser',
    size: '~400 MB',
    parameters: '0.6B',
    provider: 'Alibaba',
    paramCount: 600000000,
    releaseDate: '2025-03-25',
    recommended: true,
    tags: ['thinking'],
  },
  {
    id: 'Qwen3-1.7B-q4f16_1-MLC',
    name: 'Qwen 3 1.7B',
    description: 'Alibaba Qwen 3 - balanced performance and quality',
    size: '~1 GB',
    parameters: '1.7B',
    provider: 'Alibaba',
    paramCount: 1700000000,
    releaseDate: '2025-03-25',
    tags: ['thinking'],
  },
  {
    id: 'Qwen3-4B-q4f16_1-MLC',
    name: 'Qwen 3 4B',
    description: 'Alibaba Qwen 3 - stronger reasoning, needs better GPU',
    size: '~2.5 GB',
    parameters: '4B',
    provider: 'Alibaba',
    paramCount: 4000000000,
    releaseDate: '2025-03-25',
    tags: ['thinking'],
  },
  {
    id: 'Qwen3.5-0.8B-q4f16_1-MLC',
    name: 'Qwen 3.5 0.8B',
    description: 'Alibaba Qwen 3.5 - latest generation, ultra lightweight',
    size: '~500 MB',
    parameters: '0.8B',
    provider: 'Alibaba',
    paramCount: 800000000,
    releaseDate: '2025-05-20',
    tags: ['thinking', 'tools'],
  },
  {
    id: 'Qwen3.5-2B-q4f16_1-MLC',
    name: 'Qwen 3.5 2B',
    description: 'Alibaba Qwen 3.5 - improved over Qwen 3, balanced performance',
    size: '~1.2 GB',
    parameters: '2B',
    provider: 'Alibaba',
    paramCount: 2000000000,
    releaseDate: '2025-05-20',
    tags: ['thinking', 'tools'],
  },
  {
    id: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 0.5B',
    description: 'Alibaba Qwen 2.5 - ultra lightweight, fast inference',
    size: '~350 MB',
    parameters: '0.5B',
    provider: 'Alibaba',
    paramCount: 500000000,
    releaseDate: '2024-09-19',
    recommended: true,
    tags: ['thinking'],
  },
  {
    id: 'Qwen2.5-1.5B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 1.5B',
    description: 'Alibaba Qwen 2.5 - balanced performance and quality',
    size: '~900 MB',
    parameters: '1.5B',
    provider: 'Alibaba',
    paramCount: 1500000000,
    releaseDate: '2024-09-19',
    tags: ['thinking'],
  },
  {
    id: 'SmolLM2-360M-Instruct-q4f16_1-MLC',
    name: 'SmolLM2 360M',
    description: 'HuggingFace SmolLM2 - smallest and fastest',
    size: '~200 MB',
    parameters: '360M',
    provider: 'HuggingFace',
    paramCount: 360000000,
    releaseDate: '2024-09-03',
    tags: ['thinking'],
  },
  {
    id: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC',
    name: 'SmolLM2 1.7B',
    description: 'HuggingFace SmolLM2 - stronger reasoning capability',
    size: '~1 GB',
    parameters: '1.7B',
    provider: 'HuggingFace',
    paramCount: 1700000000,
    releaseDate: '2024-09-03',
    tags: ['thinking'],
  },
  {
    id: 'gemma-2-2b-it-q4f16_1-MLC',
    name: 'Gemma 2 2B',
    description: 'Google Gemma 2 - high quality small model',
    size: '~1.3 GB',
    parameters: '2B',
    provider: 'Google',
    paramCount: 2000000000,
    releaseDate: '2024-06-27',
    tags: ['thinking'],
  },
  {
    id: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
    name: 'Phi 3.5 Mini',
    description: 'Microsoft Phi 3.5 Mini - strong reasoning for its size',
    size: '~2 GB',
    parameters: '3.8B',
    provider: 'Microsoft',
    paramCount: 3800000000,
    releaseDate: '2024-06-04',
    tags: ['thinking'],
  },
  {
    id: 'TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC',
    name: 'TinyLlama 1.1B',
    description: 'TinyLlama - community favorite compact model',
    size: '~600 MB',
    parameters: '1.1B',
    provider: 'Community',
    paramCount: 1100000000,
    releaseDate: '2023-08-15',
    tags: ['thinking'],
  },
  // --- New models added in this update ---

  {
    id: 'DeepSeek-R1-Distill-Qwen-1.5B-q4f16_1-MLC',
    name: 'DeepSeek R1 Distill Qwen 1.5B',
    description: 'DeepSeek R1 distilled to Qwen 1.5B - strong reasoning, lightweight',
    size: '~1 GB',
    parameters: '1.5B',
    provider: 'DeepSeek',
    paramCount: 1500000000,
    releaseDate: '2025-01-28',
    recommended: true,
    tags: ['thinking'],
  },
  {
    id: 'gemma-3-4b-it-q4f16_1-MLC',
    name: 'Gemma 3 4B',
    description: 'Google Gemma 3 - next-gen small model, strong reasoning',
    size: '~2.5 GB',
    parameters: '4B',
    provider: 'Google',
    paramCount: 4000000000,
    releaseDate: '2025-03-12',
    recommended: true,
    tags: ['thinking'],
  },
  // --- Meta Llama ---
  {
    id: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
    name: 'Llama 3.2 1B',
    description: 'Meta Llama 3.2 - lightweight, fast inference, great for mobile',
    size: '~700 MB',
    parameters: '1B',
    provider: 'Meta',
    paramCount: 1000000000,
    releaseDate: '2024-09-25',
    tags: ['thinking'],
  },
  {
    id: 'Llama-3.2-3B-Instruct-q4f16_1-MLC',
    name: 'Llama 3.2 3B',
    description: 'Meta Llama 3.2 - stronger reasoning, multilingual support',
    size: '~1.8 GB',
    parameters: '3B',
    provider: 'Meta',
    paramCount: 3000000000,
    releaseDate: '2024-09-25',
    recommended: true,
    tags: ['thinking'],
  },
  // --- Microsoft Phi ---
  {
    id: 'Phi-4-mini-instruct-q4f16_1-MLC',
    name: 'Phi 4 Mini',
    description: 'Microsoft Phi 4 Mini - state-of-the-art 3.8B reasoning model',
    size: '~2.2 GB',
    parameters: '3.8B',
    provider: 'Microsoft',
    paramCount: 3800000000,
    releaseDate: '2025-02-04',
    recommended: true,
    tags: ['thinking'],
  },
  // --- Google Gemma ---
  {
    id: 'gemma-3-1b-it-q4f16_1-MLC',
    name: 'Gemma 3 1B',
    description: 'Google Gemma 3 - ultra-compact next-gen model',
    size: '~700 MB',
    parameters: '1B',
    provider: 'Google',
    paramCount: 1000000000,
    releaseDate: '2025-03-12',
    tags: ['thinking'],
  },
  // --- Alibaba Qwen ---
  {
    id: 'Qwen2.5-3B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 3B',
    description: 'Alibaba Qwen 2.5 - strong mid-range model with good multilingual support',
    size: '~1.8 GB',
    parameters: '3B',
    provider: 'Alibaba',
    paramCount: 3000000000,
    releaseDate: '2024-09-19',
    tags: ['thinking'],
  },
  {
    id: 'Qwen2.5-Coder-1.5B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 Coder 1.5B',
    description: 'Alibaba Qwen 2.5 Coder - specialized for code generation and completion',
    size: '~900 MB',
    parameters: '1.5B',
    provider: 'Alibaba',
    paramCount: 1500000000,
    releaseDate: '2024-11-12',
    tags: ['thinking', 'tools'],
  },
  // --- Stability AI ---
  {
    id: 'stablelm-2-zephyr-1_6b-q4f16_1-MLC',
    name: 'StableLM 2 Zephyr 1.6B',
    description: 'Stability AI StableLM 2 Zephyr - chat-tuned, efficient 1.6B model',
    size: '~950 MB',
    parameters: '1.6B',
    provider: 'Stability AI',
    paramCount: 1600000000,
    releaseDate: '2024-01-19',
    tags: ['thinking'],
  },
  // --- Shanghai AI Lab ---
  {
    id: 'internlm2_5-1_8b-chat-q4f16_1-MLC',
    name: 'InternLM 2.5 1.8B',
    description: 'Shanghai AI Lab InternLM 2.5 - strong chat model with tool-use capability',
    size: '~1.1 GB',
    parameters: '1.8B',
    provider: 'Shanghai AI Lab',
    paramCount: 1800000000,
    releaseDate: '2024-07-03',
    tags: ['thinking', 'tools'],
  },
  // --- Allen Institute ---
  {
    id: 'OLMo-1B-0724-SFT-q4f16_1-MLC',
    name: 'OLMo 1B',
    description: 'Allen Institute OLMo - fully open-source language model, transparent training',
    size: '~600 MB',
    parameters: '1B',
    provider: 'Allen Institute',
    paramCount: 1000000000,
    releaseDate: '2024-07-01',
    tags: ['thinking'],
  },
]

export function getModelById(id: string): ModelInfo | undefined {
  return MODELS.find((m) => m.id === id)
}
