import type { ModelInfo } from '../types'

export const MODELS: ModelInfo[] = [
  {
    id: 'Qwen3-0.6B-q4f16_1-MLC',
    name: 'Qwen 3 0.6B',
    description: 'Alibaba Qwen 3 - latest generation, ultra lightweight for browser',
    size: '~400 MB',
    parameters: '0.6B',
    provider: 'Alibaba',
    recommended: true,
    tags: ['thinking'],
  },
  {
    id: 'Qwen3-1.7B-q4f16_1-MLC',
    name: 'Qwen 3 1.7B',
    description: 'Alibaba Qwen 3 - balanced performance and quality',
    size: '~1 GB',
    parameters: '1.7B',
    provider: 'Alibaba',
    tags: ['thinking'],
  },
  {
    id: 'Qwen3-4B-q4f16_1-MLC',
    name: 'Qwen 3 4B',
    description: 'Alibaba Qwen 3 - stronger reasoning, needs better GPU',
    size: '~2.5 GB',
    parameters: '4B',
    provider: 'Alibaba',
    tags: ['thinking'],
  },
  {
    id: 'Qwen3-8B-q4f16_1-MLC',
    name: 'Qwen 3 8B',
    description: 'Alibaba Qwen 3 - best quality, requires powerful GPU',
    size: '~5 GB',
    parameters: '8B',
    provider: 'Alibaba',
    tags: ['thinking'],
  },
  {
    id: 'Qwen3.5-0.8B-q4f16_1-MLC',
    name: 'Qwen 3.5 0.8B',
    description: 'Alibaba Qwen 3.5 - latest generation, ultra lightweight',
    size: '~500 MB',
    parameters: '0.8B',
    provider: 'Alibaba',
    tags: ['thinking', 'tools'],
  },
  {
    id: 'Qwen3.5-2B-q4f16_1-MLC',
    name: 'Qwen 3.5 2B',
    description: 'Alibaba Qwen 3.5 - improved over Qwen 3, balanced performance',
    size: '~1.2 GB',
    parameters: '2B',
    provider: 'Alibaba',
    tags: ['thinking', 'tools'],
  },
  {
    id: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 0.5B',
    description: 'Alibaba Qwen 2.5 - ultra lightweight, fast inference',
    size: '~350 MB',
    parameters: '0.5B',
    provider: 'Alibaba',
    recommended: true,
    tags: ['thinking'],
  },
  {
    id: 'Qwen2.5-1.5B-Instruct-q4f16_1-MLC',
    name: 'Qwen 2.5 1.5B',
    description: 'Alibaba Qwen 2.5 - balanced performance and quality',
    size: '~900 MB',
    parameters: '1.5B',
    provider: 'Alibaba',
    tags: ['thinking'],
  },
  {
    id: 'SmolLM2-360M-Instruct-q4f16_1-MLC',
    name: 'SmolLM2 360M',
    description: 'HuggingFace SmolLM2 - smallest and fastest',
    size: '~200 MB',
    parameters: '360M',
    provider: 'HuggingFace',
    tags: ['thinking'],
  },
  {
    id: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC',
    name: 'SmolLM2 1.7B',
    description: 'HuggingFace SmolLM2 - stronger reasoning capability',
    size: '~1 GB',
    parameters: '1.7B',
    provider: 'HuggingFace',
    tags: ['thinking'],
  },
  {
    id: 'gemma-2-2b-it-q4f16_1-MLC',
    name: 'Gemma 2 2B',
    description: 'Google Gemma 2 - high quality small model',
    size: '~1.3 GB',
    parameters: '2B',
    provider: 'Google',
    tags: ['thinking'],
  },
  {
    id: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
    name: 'Phi 3.5 Mini',
    description: 'Microsoft Phi 3.5 Mini - strong reasoning for its size',
    size: '~2 GB',
    parameters: '3.8B',
    provider: 'Microsoft',
    tags: ['thinking'],
  },
  {
    id: 'TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC',
    name: 'TinyLlama 1.1B',
    description: 'TinyLlama - community favorite compact model',
    size: '~600 MB',
    parameters: '1.1B',
    provider: 'Community',
    tags: ['thinking'],
  },
]

export function getModelById(id: string): ModelInfo | undefined {
  return MODELS.find((m) => m.id === id)
}
